### ISSUE TITLE
Rewrite redirect logic

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/mi-icecast-redirect-service#1]
Move from the current structure:
proto://server/group/example/streamkey/example.mp3

To:
proto://server/redirect-proto/redirect-port/group/streamkey

**Example HTTPS**: 
- https://redirect.server.com/https/443/example1/example.mp3

This response will be: 
 - https://icecast-server.com/example.mp3

**Example HTTP + Custom Port**: 
- http://redirect.server.com/http/8000/example1/example.mp3

This response will be: 
 - http://icecast-server.com:8000/example.mp3

Notes: 

- if PROTO is HTTPS and port 443 (default https) don't add into the redirect.
- if PROTO is HTTP and port 80 (default http) don't add into the redirect.

**Comment by jonathanbrenman** [comment]
Done.
